--Nome: Caike Dametto RM: 558614
--Nome: Guilhetme Janunzzi RM: 558461

--Top 5 Voluntários Mais Ativos por Atendimentos Concluídos

SELECT
    NM_USUARIO,
    DS_EMAIL,
    TOTAL_ATENDIMENTOS_CONCLUIDOS
FROM (
    SELECT
        u.NM_USUARIO,
        u.DS_EMAIL,
        COUNT(av.CD_ATENDIMENTO) AS TOTAL_ATENDIMENTOS_CONCLUIDOS,
        ROW_NUMBER() OVER (ORDER BY COUNT(av.CD_ATENDIMENTO) DESC) as rn
    FROM
        T_EH_USUARIO u
    JOIN
        T_EH_ATENDIMENTO_VOLUNTARIO av ON u.CD_USUARIO = av.CD_USUARIO
    WHERE
        u.DS_TIPO = 'VOLUNTARIO' 
        AND av.DT_MOMENTO_CONCLUSAO IS NOT NULL 
    GROUP BY
        u.CD_USUARIO, u.NM_USUARIO, u.DS_EMAIL
    HAVING
        COUNT(av.CD_ATENDIMENTO) > 0 
)
WHERE rn <= 5
ORDER BY
    TOTAL_ATENDIMENTOS_CONCLUIDOS DESC, NM_USUARIO ASC;