--Nome: Caike Dametto RM: 558614
--Nome: Guilhetme Janunzzi RM: 558461

DROP TABLE T_EH_USUARIO CASCADE CONSTRAINTS;

DROP TABLE T_EH_PEDIDO_AJUDA CASCADE CONSTRAINTS;

DROP TABLE T_EH_ATENDIMENTO_VOLUNTARIO CASCADE CONSTRAINTS;

DROP TABLE T_EH_ALERTA CASCADE CONSTRAINTS;

DROP TABLE T_EH_DICA_PREPARACAO CASCADE CONSTRAINTS;